version: '2'
services:
    projectmicroservices-app:
        image: projectmicroservices
        external_links:
            - projectmicroservices-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/projectmicroservices?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    projectmicroservices-mysql:
        extends:
            file: mysql.yml
            service: projectmicroservices-mysql
